package views;

import javax.swing.*;
import java.awt.*;

public class GameplayFrame {
    private JPanel mainPanel;
    private JPanel informationPanel;
    private JPanel centerPanel;
    private JPanel info1;
    private JPanel buttons;
    private JPanel info2;
    private JButton button1;

    public static void Run() {
        JFrame frame = new JFrame("Gameplay");
        frame.setContentPane(new GameplayFrame().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);
        //opens in the center of the monitor
        frame.setLocationRelativeTo(null);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        mainPanel.setPreferredSize(new Dimension(1200, 900));
        centerPanel.setPreferredSize(new Dimension(900, 900));
        informationPanel.setPreferredSize(new Dimension(300, 900));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBackground(new Color(-1312769));
        mainPanel.setEnabled(false);
        mainPanel.setVisible(true);
        informationPanel = new JPanel();
        informationPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        informationPanel.setPreferredSize(new Dimension(300, 900));
        mainPanel.add(informationPanel, BorderLayout.EAST);
        info1 = new JPanel();
        info1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        info1.setPreferredSize(new Dimension(300, 200));
        informationPanel.add(info1);
        buttons = new JPanel();
        buttons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        buttons.setPreferredSize(new Dimension(300, 400));
        informationPanel.add(buttons);
        button1 = new JButton();
        button1.setText("Button");
        buttons.add(button1);
        info2 = new JPanel();
        info2.setLayout(new BorderLayout(0, 0));
        info2.setPreferredSize(new Dimension(300, 300));
        informationPanel.add(info2);
        centerPanel = new JPanel();
        centerPanel.setLayout(new BorderLayout(0, 0));
        centerPanel.setPreferredSize(new Dimension(900, 900));
        mainPanel.add(centerPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


}
